### ISSUE TITLE
What is this probleM?

### ISSUE THREAD

**Issue by NakiriYuuzu** [OHYeah0202/CPE#1]
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

 

Example 1:

Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
Example 2:

Input: nums = [3,2,4], target = 6
Output: [1,2]
Example 3:

Input: nums = [3,3], target = 6
Output: [0,1]

**Comment by OHYeah0202** [comment]
The problem try to find two numbers in an array that sum up will hit the target you're looking for. You need to return the index of the two numbers in the array. Hope this can help you.😁

**Comment by NakiriYuuzu** [comment]
> The problem try to find two numbers in an array that sum up will hit the target you're looking for.

give me the code with any programming language.

**Comment by NakiriYuuzu** [comment]
like this?
```kotlin
fun main() {
    fun twoSum(nums: IntArray, target: Int): IntArray {
        val map = mutableMapOf<Int, Int>()
        nums.forEachIndexed { index, i ->
            if (map.containsKey(target - i)) {
                return intArrayOf(map[target - i]!!, index)
            }
            map[i] = index
        }
        return intArrayOf()
    }

    val nums = intArrayOf(2, 7, 11, 15)
    val target = 9
    println(twoSum(nums, target).contentToString())
}
```

**Comment by OHYeah0202** [comment]
> > The problem try to find two numbers in an array that sum up will hit the target you're looking for.
> 
> give me the code with any programming language.

```
def twoSum(nums, target):
    num_dict = {}
    print(type(num_dict))
    
    for i, num in enumerate(nums):
        print(num)
        complement = target - num
        
        print(complement in num_dict)
        if complement in num_dict:
            return [num_dict[complement], i]
        
        num_dict[num] = i

# Test Data
nums1 = [2, 7, 11, 15]
target1 = 9
result1 = twoSum(nums1, target1)
print(result1)  # Output [0, 1]

nums2 = [3, 2, 4]
target2 = 6
result2 = twoSum(nums2, target2)
print(result2)  # Output [1, 2]

nums3 = [3, 3]
target3 = 6
result3 = twoSum(nums3, target3)
print(result3)  # Output [0, 1]
```

**Comment by NakiriYuuzu** [comment]
666

**Comment by OHYeah0202** [comment]
Presented by ChatGPT
